### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alvarogzp** [alvarogzp/man-in-the-middle#1]
If you would like to contribute, here are some things that would be nice to have implemented.
Feel free to send a pull request, or create new issues.

- [ ] avoid blocking sockets to stall forever in SocketStreamForwarder (using timeouts)
- [ ] when a request ends on one side, end it on the other side and stop all threads related to it
- [ ] report exceptions in SocketStreamForwarder?
- [ ] add setup.py
